### PR TITLE
cfg: error if specified config file is missing.

### LINKED ISSUE #835: dcrwallet should not continue when specified config file is not present
```
jcv@triforce ~ $ dcrwallet -C .dcrwallet-main/
10:49:00.519 2017-07-06 [WRN] DCRW: read .dcrwallet-main: is a directory
10:49:00.520 2017-07-06 [INF] DCRW: Version 1.0.4+dev (Go version go1.8.3)
10:49:01.203 2017-07-06 [INF] WLLT: Opened wallet
```

In that example, I incorrectly specified a config file with `-C` and things kept running with the default config which can lead to confusing errors.

### PR DESCRIPTION
**Pull request by jcvernaleo**
If no file is specified, the current behavior (warn only)
if correct and is not changed.

Closes #835

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -496,6 +496,13 @@ func loadConfig() (*config, []string, error) {
 		return loadConfigError(err)
 	}
 
+	// Error and shutdown if config file is specified on the command line
+	// but cannot be found.
+	if (configFileError != nil) && (configFilePath != defaultConfigFile) {
```
Comment (jrick) [inline config.go]: can you remove the unnecessary parentheses?

Comment (jcvernaleo) [inline config.go]: Removed.
