### PR TITLE
Replace chainec.Sign with secp256k1.SignCompact in SignMessge RPC

### LINKED ISSUE #248: signmessage uses wrong signature method
Should use SignCompact instead of Sign. In order to do this it will have to directly import the secp256k1 API instead of using the chainec wrapper.

https://github.com/decred/dcrwallet/blob/master/rpc/legacyrpc/methods.go#L3205

### PR DESCRIPTION
**Pull request by alexlyp**
Fixes #248

### CODE REVIEW

**Comment by cjepson** [comment]
Does validatemessage work correctly now in dcrd with this update?

File: rpc/legacyrpc/methods.go [hunk 1]
```diff
@@ -3202,13 +3203,17 @@ func signMessage(icmd interface{}, w *wallet.Wallet) (interface{}, error) {
 	wire.WriteVarString(&buf, 0, "Decred Signed Message:\n")
 	wire.WriteVarString(&buf, 0, cmd.Message)
 	messageHash := chainhash.HashFuncB(buf.Bytes())
-	r, s, err := chainec.Secp256k1.Sign(privKey, messageHash)
+	pkCast, ok := privKey.(*secp256k1.PrivateKey)
+	if !ok {
+		return nil, fmt.Errorf("Unable to create secp256k1.PrivateKey" +
```
Comment (jrick) [inline rpc/legacyrpc/methods.go]: I wouldn't use actual type names here since this is possible to hit as a user by using a non-secp256k1 P2PKH address.  Instead, I would say something such as "The address must correspond to a secp256k1 public key", and perhaps even include in the error what type of DSA and/or curve the address actually represents.

**Comment by cjepson** [comment]
Any updates?

**Comment by alexlyp** [comment]
tACK with signmessage on wallet and verifymesasge on dcrd
