### PR TITLE
chain: Close RPC conn on bad server version.

### LINKED ISSUE #1542: Reconnection to dcrd fails after 25 attempts
#### Steps to reproduce:
- Build dcrd 1.4.0
- Build dcrwallet master
- Run dcrd and dcrwallet

#### Expected result:
- dcrwallet logs an error about incompatible RPC version
- Reconnection attempted indefinitely

#### Actual result:
- dcrwallet logs an error about incompatible RPC version
- dcrwallet attempts to reconnect indefinitely, but after 25 times dcrd begins to log the following:

```
2019-08-30 13:27:59.840 [INF] RPCS: New websocket client 127.0.0.1:55288
2019-08-30 13:28:00.760 [INF] RPCS: New websocket client 127.0.0.1:55290
2019-08-30 13:28:04.894 [INF] RPCS: New websocket client 127.0.0.1:55292
2019-08-30 13:28:05.812 [INF] RPCS: New websocket client 127.0.0.1:55294
2019-08-30 13:28:09.949 [INF] RPCS: New websocket client 127.0.0.1:55296
2019-08-30 13:28:10.848 [INF] RPCS: New websocket client 127.0.0.1:55298
2019-08-30 13:28:15.009 [INF] RPCS: New websocket client 127.0.0.1:55300
2019-08-30 13:28:15.889 [INF] RPCS: New websocket client 127.0.0.1:55302
2019-08-30 13:28:20.047 [INF] RPCS: New websocket client 127.0.0.1:55304
2019-08-30 13:28:20.944 [INF] RPCS: New websocket client 127.0.0.1:55306
2019-08-30 13:28:25.122 [INF] RPCS: New websocket client 127.0.0.1:55308
2019-08-30 13:28:25.992 [INF] RPCS: New websocket client 127.0.0.1:55310
2019-08-30 13:28:30.153 [INF] RPCS: New websocket client 127.0.0.1:55312
2019-08-30 13:28:30.153 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55312
2019-08-30 13:28:31.048 [INF] RPCS: New websocket client 127.0.0.1:55314
2019-08-30 13:28:31.048 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55314
2019-08-30 13:28:35.206 [INF] RPCS: New websocket client 127.0.0.1:55316
2019-08-30 13:28:35.206 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55316
2019-08-30 13:28:36.097 [INF] RPCS: New websocket client 127.0.0.1:55318
2019-08-30 13:28:36.097 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55318
2019-08-30 13:28:40.249 [INF] RPCS: New websocket client 127.0.0.1:55320
2019-08-30 13:28:40.249 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55320
2019-08-30 13:28:41.158 [INF] RPCS: New websocket client 127.0.0.1:55322
2019-08-30 13:28:41.158 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55322
2019-08-30 13:28:45.307 [INF] RPCS: New websocket client 127.0.0.1:55326
2019-08-30 13:28:45.307 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55326
2019-08-30 13:28:46.201 [INF] RPCS: New websocket client 127.0.0.1:55328
2019-08-30 13:28:46.201 [INF] RPCS: Max websocket clients exceeded [25] - disconnecting client 127.0.0.1:55328
```

_(Originally discovered in decred/dcrstakepool#510)_

### PR DESCRIPTION
**Pull request by jholdstock**
Closes #1542 

We may need further changes in this Run() function to close the client in other places where an error is returned.

### CODE REVIEW

File: chain/sync.go [hunk 1]
```diff
@@ -267,6 +267,7 @@ func (s *Syncer) Run(ctx context.Context) (err error) {
 		return err
 	}
 	if !semverCompatible(requiredAPIVersion, api.Version) {
+		client.Close()
```
Comment (jrick) [inline chain/sync.go]: good catch that we need to close this, but let's instead do it with a defer so it happens on all error paths

```
client, err := wsrpc.Dial(...)
if err != nil {
  // ...
}
defer client.Close()
```
