### PR TITLE
Fix output mixing from using lowest denom with insane fees

### LINKED ISSUE #2000: Huge mixing fee from version 1.6.1
My wallet just created this transaction where most of dcr from input#1 goes to fee. Must be a bug!

https://explorer.dcrdata.org/tx/05fee1f807888b623b98692797daf998a3dcf9d4b021f9e38af87e51f9be0b16

### PR DESCRIPTION
**Pull request by jrick**
The mixValue variable was not being assigned to the expected value in
the splitPoints array, causing the loop to skip to the last common mix
denomination and result in an insane fee contributed to the coinjoin
transaction due to the mixed output count being limited to a maximum
of four per input.

Fixes #2000.

### CODE REVIEW

File: wallet/mixing.go [hunk 1]
```diff
@@ -105,6 +105,7 @@ func (w *Wallet) MixOutput(ctx context.Context, dialTLS DialFunc, csppserver str
 SplitPoints:
 	for i = 0; i < len(splitPoints); i++ {
 		last := i == len(splitPoints)-1
+		mixValue = splitPoints[i]
```
Comment (chappjc) [inline wallet/mixing.go:108]: Prior to https://github.com/decred/dcrwallet/pull/1995/commits/d479a125eb66c956522832a764afbee9df4145e7, there was a `range` instead, which actually seems better here.  Any reason not to stick with `for i, mixValue = range splitPoints`?

Comment (jrick) [reply wallet/mixing.go:108]: We need to see if we iterated past the last item in the array, `i` is declared before this loop and checked immediately after.

**Review by alexlyp — APPROVED** [review]
