### PR TITLE
ticketbuyer: Fix panic on shutdown

### LINKED ISSUE #482: panic on shutdown
I was able to hit a panic when shutting down wallet with the rpc command:
```
13:17:23 2016-12-20 [INF] DCRW: Received shutdown request.  Shutting down...
13:17:23 2016-12-20 [WRN] DCRW: Stopping legacy RPC server...
13:17:23 2016-12-20 [INF] TKBY: Stopping ticket buyer
unexpected fault address 0x235789008
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x235789008 pc=0x998d29]

goroutine 66 [running]:
runtime.throw(0xbb141c, 0x5)
        /home/jcv/code/golang/src/runtime/panic.go:566 +0x95 fp=0xc420116b78 sp=0xc420116b58
runtime.sigpanic()
        /home/jcv/code/golang/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc420116bd0 sp=0xc420116b78
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0x15697)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:255 +0x69 fp=0xc420116c98 sp=0xc420116bd0
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).searchPage(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0x22cad8000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:314 +0x13c fp=0xc420116d28 sp=0xc420116c98
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0xc9e6)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:271 +0x1b6 fp=0xc420116df0 sp=0xc420116d28
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).searchPage(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0x226d0e000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:314 +0x13c fp=0xc420116e80 sp=0xc420116df0
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).search(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0x6c1c)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:271 +0x1b6 fp=0xc420116f48 sp=0xc420116e80
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).seek(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0x0, 0xc42045c000, 0xc421e5f601, 0x267ba4000, 0x0, 0xb11920, ...)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:159 +0xb1 fp=0xc420116f98 sp=0xc420116f48
github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt.(*Cursor).Seek(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0xc422809701, 0xc4200138c0, 0xc420117060, 0x41feef, 0xb59160, 0xc4200138c0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/boltdb/bolt/cursor.go:118 +0x50 fp=0xc420117000 sp=0xc420116f98
github.com/decred/dcrwallet/walletdb/bdb.(*cursor).Seek(0xc422809740, 0x22dc0c030, 0x44, 0x44, 0xc4200138c0, 0x1077580, 0xc4200138c0, 0xc420019b40, 0x2ad314f40, 0xc422809740)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/walletdb/bdb/db.go:270 +0x4d fp=0xc420117060 sp=0xc420117000
github.com/decred/dcrwallet/wtxmgr.(*readCursor).Seek(0xc4200138c0, 0x22dc0c030, 0x44, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        <autogenerated>:12 +0x6b fp=0xc4201170c0 sp=0xc420117060
github.com/decred/dcrwallet/wtxmgr.(*creditIterator).next(0xc4201173c0, 0xc421e5f640)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wtxmgr/db.go:1164 +0x211 fp=0xc420117140 sp=0xc4201170c0
github.com/decred/dcrwallet/wtxmgr.(*Store).minedTxDetails(0xc430afc0c0, 0x206be7c20, 0xc421e5f640, 0xc425a72660, 0x22dc0c030, 0x44, 0x44, 0x22dc0c074, 0x5f5, 0x5f5, ...)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wtxmgr/query.go:73 +0x217 fp=0xc420117450 sp=0xc420117140
github.com/decred/dcrwallet/wtxmgr.(*Store).TxDetails(0xc430afc0c0, 0x206be7c20, 0xc421e5f640, 0xc425a72660, 0x0, 0x0, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wtxmgr/query.go:193 +0x18e fp=0xc4201174c8 sp=0xc420117450
github.com/decred/dcrwallet/wallet.(*Wallet).StakeInfo.func1(0x1070ce0, 0xc42002a418, 0xc42002a418, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/wallet.go:2971 +0xbf4 fp=0xc4201177f0 sp=0xc4201174c8
github.com/decred/dcrwallet/walletdb.View(0x10751a0, 0xc4204c43c0, 0xc420117878, 0x0, 0x636daa)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/walletdb/interface.go:197 +0x6f fp=0xc420117848 sp=0xc4201177f0
github.com/decred/dcrwallet/wallet.(*Wallet).StakeInfo(0xc42000c6c0, 0x63692e, 0xc420445100, 0x1)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/wallet/wallet.go:3044 +0x9a fp=0xc4201178a8 sp=0xc420117848
github.com/decred/dcrwallet/ticketbuyer.(*TicketPurchaser).ownTicketsInMempool(0xc4200e83c0, 0x404a538155551c11, 0x77, 0xc421e5f580)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/mempool.go:73 +0x6e fp=0xc420117970 sp=0xc4201178a8
github.com/decred/dcrwallet/ticketbuyer.(*TicketPurchaser).Purchase(0xc4200e83c0, 0x3883b, 0x19, 0xc4250a2000, 0x1)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/buyer.go:481 +0xac7 fp=0xc420117e58 sp=0xc420117970
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).purchase(0xc420622020, 0x3883b)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:35 +0xf8 fp=0xc420117ee0 sp=0xc420117e58
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc420444a00, 0xc420622020, 0xc4206442a0, 0xc420644300)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:54 +0xd3 fp=0xc420117f80 sp=0xc420117ee0
runtime.goexit()
        /home/jcv/code/golang/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420117f88 sp=0xc420117f80
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 1 [runnable]:
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLogger).Flush(0xc420445100)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclogger.go:87
main.walletMain(0x0, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/dcrwallet.go:205 +0x881
main.main()
        /home/jcv/code/go/src/github.com/decred/dcrwallet/dcrwallet.go:39 +0x32

goroutine 5 [semacquire, 30 minutes]:
sync.runtime_notifyListWait(0xc420019a50, 0x0)
        /home/jcv/code/golang/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420019a40)
        /home/jcv/code/golang/src/sync/cond.go:57 +0x80
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc420016960, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x97
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc420016960)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x33
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncLoopLogger
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x96

goroutine 6 [semacquire, 30 minutes]:
sync.runtime_notifyListWait(0xc420019c50, 0x0)
        /home/jcv/code/golang/src/runtime/sema.go:267 +0x122
sync.(*Cond).Wait(0xc420019c40)
        /home/jcv/code/golang/src/sync/cond.go:57 +0x80
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processItem(0xc420016a80, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:50 +0x97
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLoopLogger).processQueue(0xc420016a80)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:63 +0x33
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncLoopLogger
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclooplogger.go:40 +0x96

goroutine 37 [syscall, 30 minutes]:
os/signal.signal_recv(0xc420029fa8)
        /home/jcv/code/golang/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /home/jcv/code/golang/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /home/jcv/code/golang/src/os/signal/signal_unix.go:28 +0x41

goroutine 38 [runnable]:
fmt.(*pp).doPrint(0xc4243180c0, 0xc421d8f4e0, 0x2, 0x2)
        /home/jcv/code/golang/src/fmt/print.go:1105
fmt.Sprint(0xc421d8f4e0, 0x2, 0x2, 0xc42558d680, 0x0)
        /home/jcv/code/golang/src/fmt/print.go:232 +0x56
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*logMessage).String(0xc421d8f500, 0xd6db02, 0x1077be0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/logger.go:365 +0x40
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*commonLogger).processLogMsg(0xc420445100, 0xb30002, 0x106c620, 0xc421d8f500, 0x1077be0, 0xc4200174a0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/logger.go:312 +0x9c
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncLogger).processQueueElement(0xc420445100)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_asynclogger.go:112 +0x118
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncAdaptiveLogger).processItem(0xc420445100, 0xc423ee4900, 0x0)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:101 +0xcd
github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.(*asyncAdaptiveLogger).processQueue(0xc420445100)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:119 +0x37
created by github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog.newAsyncAdaptiveLogger
        /home/jcv/code/go/src/github.com/decred/dcrwallet/vendor/github.com/btcsuite/seelog/behavior_adaptivelogger.go:84 +0x1b5

goroutine 12 [select, 29 minutes, locked to thread]:
runtime.gopark(0xd6f140, 0x0, 0xbb29e5, 0x6, 0x18, 0x2)
        /home/jcv/code/golang/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420105730, 0x0, 0x18)
        /home/jcv/code/golang/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420105730)
        /home/jcv/code/golang/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /home/jcv/code/golang/src/runtime/signal1_unix.go:304 +0x2d6
runtime.goexit()
        /home/jcv/code/golang/src/runtime/asm_amd64.s:2086 +0x1

goroutine 24 [chan receive, 24 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc42154e000, 0xc420622020, 0xc420644300, 0xc423c06000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 98 [chan receive, 3 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc431156200, 0xc420622020, 0xc421d14000, 0xc423ed4000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 26 [chan receive, 13 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc431156180, 0xc420622020, 0xc42149a000, 0xc423fde000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 83 [chan receive, 16 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc431294100, 0xc420622020, 0xc423c06000, 0xc42149a000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 85 [chan receive, 10 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc431156100, 0xc420622020, 0xc423fde000, 0xc423c06060)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162

goroutine 86 [chan receive, 6 minutes]:
github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler.func1(0xc42154e180, 0xc420622020, 0xc423c06060, 0xc421d14000)
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:52 +0x55
created by github.com/decred/dcrwallet/ticketbuyer.(*PurchaseManager).NotificationHandler
        /home/jcv/code/go/src/github.com/decred/dcrwallet/ticketbuyer/purchase.go:57 +0x162
jcv@yoshi ~ $
```
This was with wallet master as of roughly 12/20/2016

### PR DESCRIPTION
**Pull request by tuxcanfly**
Purchase workers were trying to read the db after shutdown, causing panic.
Fixed by returning the worker when quit signal is received.

Fixes #482

### CODE REVIEW

**Comment by jrick** [comment]
I don't this is sufficient to solve the problem.  We still need to wait until all current purchasing is done before ever attempting to close the database.

**Comment by tuxcanfly** [comment]
OK, I tested with a related case where there is a backlog of purchase goroutines and there's an err somewhere (e.g. dcrd client is shutdown), in which case we need to cancel all the workers.

Looking into a fix for the main issue now, i.e close db only after purchase.

File: ticketbuyer.go [hunk 1]
```diff
@@ -196,8 +196,9 @@ func startTicketPurchase(w *wallet.Wallet, dcrdClient *dcrrpcclient.Client,
 
 	tkbyLog.Infof("Starting ticket buyer")
 
+	quit := make(chan struct{})
```
Comment (jrick) [inline ticketbuyer.go]: quit isn't used at all here. move its creation to NewTicketPurchaser.

File: ticketbuyer/mempool.go [hunk 2]
```diff
@@ -69,16 +69,22 @@ func (t *TicketPurchaser) ownTicketsInMempool() (int, error) {
...
-			time.Sleep(stakeInfoReqTryDelay)
-			continue
-		}
-		if err == nil {
-			break
+		select {
+		case <-t.quit:
+			return 0, nil
+		default:
+			curStakeInfo, err = t.wallet.StakeInfo()
```
Comment (jrick) [inline ticketbuyer/mempool.go]: Not a big fan that this can block on the RPC (and even the sleep if it errors) when the quit channel was closed, until it is read next.  I would run it from a goroutine and use the select to block on their the async result or the quit channel.

Comment (jrick) [inline ticketbuyer/mempool.go]: Might want to also consider propagating some sort of error to indicate a timeout instead of pretending it completed successfully and returning a bogus result.

File: ticketbuyer/purchase.go [hunk 3]
```diff
@@ -48,14 +51,20 @@ out:
...
-					p.purchase(int64(h))
+					// Purchase tickets for each attached block, not just for the
+					// update to the main chain.  This is probably not optimal but
+					// it matches how dcrticketbuyer worked.
+					for h := v.NewHeight - int32(len(v.AttachedBlocks)) + 1; h <= v.NewHeight; h++ {
+						p.purchase(int64(h))
+					}
+					p.wg.Done()
+				case <-p.quit:
+					return
```
Comment (jrick) [inline ticketbuyer/purchase.go]: this is not right because it will not unblock the next worker.  this will deadlock the entire thing when waiting for all workers to exit.

File: ticketbuyer/purchase.go [hunk 4]
```diff
@@ -65,4 +74,25 @@ out:
...
+func (p *PurchaseManager) WaitForShutdown() {
+	p.wg.Wait()
+}
+
+// Stop signals all purchase manager goroutines to shutdown.
+func (p *PurchaseManager) Stop() {
+	select {
+	case <-p.quit:
+	default:
+		close(p.quit)
```
Comment (jrick) [inline ticketbuyer/purchase.go]: It's not common to hit but this is not concurrent safe because the entire operation is not atomic.  Need to lock this with a mutex.

File: ticketbuyer/purchase.go [hunk 5]
```diff
@@ -65,4 +74,25 @@ out:
...
+}
+
+// Start starts the purchase manager goroutines.
+func (p *PurchaseManager) Start() {
+	p.wg.Add(1)
+	go p.NotificationHandler()
+}
+
+// WaitForShutdown blocks until all purchase manager goroutines have finished executing.
+func (p *PurchaseManager) WaitForShutdown() {
```
Comment (jrick) [inline ticketbuyer/purchase.go]: This looks right but we need to actually use it.  Not called anywhere currently.

File: ticketbuyer.go (hunk 1 above)
Comment (tuxcanfly) [inline ticketbuyer.go]: Thanks, done.

File: ticketbuyer/mempool.go (hunk 2 above)
Comment (tuxcanfly) [inline ticketbuyer/mempool.go]: Sounds good, let me do that.

File: ticketbuyer/purchase.go (hunk 5 above)
Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Yeah, we want to wait on this before calling `UnloadWallet`. Problem is the instance of `PurchaseManager` changes depending on the chain client connection, so need some way to always wait on the latest instance.

File: ticketbuyer/purchase.go (hunk 4 above)
Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Thanks, will do that.

File: ticketbuyer/purchase.go (hunk 3 above)
Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Let me check that. I thought all workers which are blocked on select would return receive quit and return early.

Comment (jrick) [inline ticketbuyer/purchase.go]: oh. yes they will. that is fine

Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: OK yeah, found an issue with `wg.Done()`. Moved it to the top and added `defer`.

File: ticketbuyer/purchase.go (hunk 5 above)
Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Tried to solve this by adding a new struct `waiter`. It used to set the wait function to the `WaitForShutdown` function of the latest `PurchaseManager` instance.

File: ticketbuyer/mempool.go (hunk 2 above)
Comment (tuxcanfly) [inline ticketbuyer/mempool.go]: Deciding against this since we have signal handling outside this, i.e. in purchase manager. In case interrupt is received, it should quit after the ongoing purchase is complete.

**Comment by tuxcanfly** [comment]
Updated to make sure we stop `ticketbuyer` before closing the db.

File: ticketbuyer/purchase.go [hunk 6]
```diff
@@ -42,27 +45,66 @@ func (p *PurchaseManager) purchase(height int64) {
...
+	p.wg.Wait()
+}
+
+// Stop signals all purchase manager goroutines to shutdown.
+func (p *PurchaseManager) Stop() {
+	p.quitMtx.Lock()
+	quit := p.quit
+	p.quitMtx.Unlock()
```
Comment (jrick) [inline ticketbuyer/purchase.go]: this entire function needs to be protected by the mutex. having two goroutines enter the select below is incorrect

File: wallet/loader.go [hunk 7]
```diff
@@ -288,6 +292,14 @@ func (l *Loader) UnloadWallet() error {
 	return nil
 }
 
+// SetWaitFn sets a variable function which needs to be waited upon before
+// unloading.
+func (l *Loader) SetWaitFn(fn func()) {
```
Comment (jrick) [inline wallet/loader.go]: I don't really care for doing it this way but with the way startup/shutdown is currently implemented, i can't think of a much better way.  #481 should take care of this though.  Can you add a TODO here to reconsider whether this is needed after that issue is resolved?

Comment (tuxcanfly) [inline wallet/loader.go]: Sure, will add that.

File: ticketbuyer/purchase.go (hunk 6 above)
Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Thanks, moved.

File: wallet/loader.go (hunk 7 above)
Comment (tuxcanfly) [inline wallet/loader.go]: Done.

File: ticketbuyer/purchase.go [hunk 8]
```diff
@@ -42,27 +45,66 @@ func (p *PurchaseManager) purchase(height int64) {
...
+				defer p.wg.Done()
+				select {
+				case <-s1: // wait for previous worker to finish
 
-				// Purchase tickets for each attached block, not just for the
-				// update to the main chain.  This is probably not optimal but
-				// it matches how dcrticketbuyer worked.
-				for h := v.NewHeight - int32(len(v.AttachedBlocks)) + 1; h <= v.NewHeight; h++ {
-					p.purchase(int64(h))
+					// Purchase tickets for each attached block, not just for the
```
Comment (jrick) [inline ticketbuyer/purchase.go]: instead of moving this code into the case block and indenting it, since the other branch returns, leave this case block empty.  Then this code can be moved after the select and keep the same indent level

Comment (tuxcanfly) [inline ticketbuyer/purchase.go]: Thanks, moved.

File: dcrwallet.go [hunk 9]
```diff
@@ -289,7 +290,13 @@ func rpcClientConnectLoop(legacyRPCServer *legacyrpc.Server, loader *wallet.Load
...
 			}
 			if cfg.EnableTicketBuyer {
-				startTicketPurchase(w, chainClient.Client, nil, cfg.tbCfg)
+				pm, err = startTicketPurchase(w, chainClient.Client, nil, cfg.tbCfg)
+				if err != nil {
+					log.Errorf("Unable to start ticket buyer: %v", err)
+					return
+				}
+				pm.Start()
+				loader.SetWaitFn(pm.WaitForShutdown)
```
Comment (jrick) [inline dcrwallet.go]: I don't see Stop called anywhere except below in this same function.  What stops the purchase manager when the wallet is stopped from e.g. gRPC?

Comment (tuxcanfly) [inline dcrwallet.go]: Yup, tested and found that calling `CloseWallet` hangs as expected, because `pm.Stop` needs to be called first, since we're waiting on `pm.WaitForShutdown`. Thanks for catching that.

Updated to add `pm.Stop` to `SetWaitFn` as well. This makes sure we stop and wait on the purchase manager whenever wallet is unloaded.

File: dcrwallet.go [hunk 10]
```diff
@@ -289,7 +290,22 @@ func rpcClientConnectLoop(legacyRPCServer *legacyrpc.Server, loader *wallet.Load
 				legacyRPCServer.SetChainServer(chainClient)
 			}
 			if cfg.EnableTicketBuyer {
-				startTicketPurchase(w, chainClient.Client, nil, cfg.tbCfg)
+				pm, err = startTicketPurchase(w, chainClient.Client, nil, cfg.tbCfg)
+				if err != nil {
+					log.Errorf("Unable to start ticket buyer: %v", err)
+					go func() {
+						loader.SetWaitFn(nil)
```
Comment (jrick) [inline dcrwallet.go]: what is the purpose of this?

Comment (tuxcanfly) [inline dcrwallet.go]: This would reset any existing handlers in case there's an error in `startTicketPurchase`. Will test this by inducing an error.

Comment (jrick) [inline dcrwallet.go]: I think it should synchronously (not in a newly spawned goroutine) remove it before the new ticket purchaser is started then

File: dcrwallet.go [hunk 11]
```diff
@@ -289,7 +290,22 @@ func rpcClientConnectLoop(legacyRPCServer *legacyrpc.Server, loader *wallet.Load
...
+					}()
+					return
+				}
+				pm.Start()
+				go func() {
```
Comment (jrick) [inline dcrwallet.go]: any reason why this is done in a new goroutine?

Comment (tuxcanfly) [inline dcrwallet.go]: Yeah, the mutex is locked when running the callbacks, so this was causing a deadlock when done in the same goroutine.

Comment (tuxcanfly) [inline dcrwallet.go]: I guess we should be a using a different mutex for this.

Comment (jrick) [inline dcrwallet.go]: That shouldn't deadlock at all though.. it'll just block this goroutine until the other finishes.

Comment (tuxcanfly) [inline dcrwallet.go]: I think what I saw was `OpenWallet` grpc command hanging up. I think that's because it calls `OpenExistingWallet` with loader lock held, then calls `loader.onLoaded` and this callback calls `SetWaitFn` which again needs the same lock.

Comment (jrick) [inline dcrwallet.go]: still confused, I don't see how this code is acquiring the loader mutex in a way that prevents the OpenExistingWallet RPC to execute.

Comment (jrick) [inline dcrwallet.go]: to clarify on my previous comment, the mutex is only held while setting the function to call, not while calling it.  that is why I don't think this can result in a deadlock.

Comment (tuxcanfly) [inline dcrwallet.go]: When `OpenWallet` grpc is called, the mutex is held by `OpenExistingWallet` at https://github.com/decred/dcrwallet/blob/master/wallet/loader.go#L194 and the function is called in `onLoaded` at https://github.com/decred/dcrwallet/blob/master/wallet/loader.go#L246. I think this was causing the deadlock since the callback was waiting for the lock which is held by `OpenExistingWallet`.

**Comment by tuxcanfly** [comment]
Thanks @jrick 

#532 redoes this by refactoring loader out to create `pkg loader` which handles the ticket buyer lifetime and simplifies main. It also allows the grpc loader service to launch and manage the ticket buyer  as necessary.
