### PR TITLE
rpctest:  fix appdata vs datadir issue

### LINKED ISSUE #340: Start consensus and wallet nodes in rpctest with --appdata
I'm currently unable to use the rpctest package because it is still trying to do things in my "real" appdata.  These programs should be called with the --appdata option set to a temporary test location to avoid this.

### PR DESCRIPTION
**Pull request by alexlyp**
From @jrick diff, only use appdata instead of both datadir and logdir.
Fixes #340

### CODE REVIEW

File: rpctest/rpcharness_test.go [hunk 1]
```diff
@@ -197,6 +197,7 @@ func testGetNewAddress(r *Harness, t *testing.T) {
 		t.Fatal(err)
 	}
 
+	time.Sleep(60 * time.Second)
```
Comment (jrick) [inline rpctest/rpcharness_test.go]: kill this

File: rpctest/node.go [hunk 2]
```diff
@@ -159,22 +146,16 @@ func (n *nodeConfig) rpcConnConfig() rpc.ConnConfig {
...
-		n.dataDir,
-	}
-	var err error
-	for _, dir := range dirs {
-		if err = os.RemoveAll(dir); err != nil {
-			log.Printf("Cannot remove dir %s: %v", dir, err)
-		}
+	if err := os.RemoveAll(n.appDataDir); err != nil {
+		log.Printf("Cannot remove dir %s: %v", n.appDataDir, err)
+		return err
```
Comment (jrick) [inline rpctest/node.go]: don't see much point to logging the error and then returning it to the caller, who will probably end up logging it again.

File: rpctest/node.go [hunk 3]
```diff
@@ -117,10 +107,7 @@ func (n *nodeConfig) arguments() []string {
 	args = append(args, fmt.Sprintf("--rpccert=%s", n.certFile))
 	// --rpckey
 	args = append(args, fmt.Sprintf("--rpckey=%s", n.keyFile))
-	if n.dataDir != "" {
-		// --datadir
-		args = append(args, fmt.Sprintf("--datadir=%s", n.dataDir))
-	}
+	args = append(args, fmt.Sprintf("--appdata=%s", n.appDataDir))
 	if n.logDir != "" {
```
Comment (jrick) [inline rpctest/node.go]: logDir is relative to the appdata dir, we don't need this arg.  Remove this along with the (now unused) dataDir and logDir fields in the node config struct.
